# Generated by Django 6.0.1 on 2026-01-27 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['employee'], name='training_as_employe_71337f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['course'], name='training_as_course__0b3eac_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['status'], name='training_as_status_3a4e13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingassignment',
            unique_together={('course', 'employee')},
        ),
    ]
